/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phuc;

import BLL.CTHD_BLL;
import BLL.SP_BLL;
import DTO.CTHD_DTO;
import DTO.NV_DTO;
import DTO.SP_DTO;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul
 */
public class CTHD extends javax.swing.JFrame {

    /**
     * Creates new form CTHD
     */
    private Execute ex;
    private static int dongia=0, sum=0;
    private String MAHD, Date, MANV;
    private int total;
    private ArrayList<SP_DTO>listsp=new ArrayList();
    private CTHD_BLL ch;
    private SP_BLL spbll;
    private static int numberofrow=5, i=0;
    private String search;
    private ArrayList <String> listmasp=new ArrayList();
    private NV_DTO user;
    public CTHD(NV_DTO user) {
        this.user = user;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb0 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        lb2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        bt2 = new javax.swing.JButton();
        lb3 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        lb4 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        bt3 = new javax.swing.JButton();
        lb5 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        lb6 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        lb7 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        lb8 = new javax.swing.JLabel();
        tf8 = new javax.swing.JTextField();
        bt4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        lb9 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        tf9 = new javax.swing.JTextField();
        tf10 = new javax.swing.JTextField();
        bt9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lb0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb0.setIcon(new javax.swing.ImageIcon("G:\\QLCH4\\QLCH\\Icons\\title.png")); // NOI18N
        lb0.setText("Chi tiết hóa đơn");

        lb1.setText("Mã hóa đơn");

        tf1.setEditable(false);
        tf3.setText(user.getManv());

        bt1.setText("Generate");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        lb2.setText("Ngày mua");

        tf2.setEditable(false);

        bt2.setText("Time");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        lb3.setText("Người bán");

        lb4.setText("Đã mua");

        tf4.setEditable(false);

        bt3.setText("Calc");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        lb5.setText("Thuế VAT");

        tf5.setEditable(false);
        tf5.setText("5000");

        lb6.setText("Tổng cộng");

        lb7.setText("Đã nhận");

        lb8.setText("Tiền thừa");

        bt4.setText("Thối lại");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MASP", "Sản Phẩm", "Số Lượng", "Đơn giá"
            }
        ));
        jScrollPane1.setViewportView(tb);

        bt5.setText("Lưu");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setText("Clear");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt7.setText("Add Row");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt8.setText("Delete Row");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        lb9.setText("Search");

        lb10.setText("Số lượng");

        bt9.setText("Thêm");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb5)
                            .addComponent(lb4)
                            .addComponent(lb7)
                            .addComponent(lb9)
                            .addComponent(lb10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt5)
                                .addGap(28, 28, 28)
                                .addComponent(bt6)
                                .addGap(18, 18, 18)
                                .addComponent(bt7)
                                .addGap(18, 18, 18)
                                .addComponent(bt8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb1)
                                    .addComponent(lb3)
                                    .addComponent(lb6)
                                    .addComponent(lb8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb0)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt2))
                                    .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt3)
                                            .addComponent(bt9)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt4)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb1)
                            .addComponent(bt1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb9))
                    .addComponent(tf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb4)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb5)
                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb6)
                    .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb8)
                    .addComponent(tf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt8)
                            .addComponent(bt7))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt5)
                            .addComponent(bt6))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        ch=new CTHD_BLL();
            String id="HD"+String.valueOf(ch.MAHD());     //Do rs.next chỉ lấy giá trị kế tiếp nên count=n-1
                tf1.setText(id);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        Time t=new Time();
        tf2.setEditable(false);
        tf2.setText(t.toString());
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        try
        {
            ex=new Execute();
            double sl;
            for(int i=0;i<tb.getRowCount();i++)
            {
                if(tb.isRowSelected(i)==true)
                {
                    sl=Double.parseDouble(String.valueOf(tb.getValueAt(i, 2)));         //Chuyển đổi phương thức từ kiểu Object sang chuỗi
                    dongia=Integer.parseInt(String.valueOf(tb.getValueAt(i, 3)));
                    sum+=ex.Res(sl, dongia);     //Cộng dồn cho mấy dòng khác
                    tf4.setText(String.valueOf(sum));
                    tf6.setText(String.valueOf(sum+5000));
                }
            } 
        }catch(NumberFormatException ne){
            System.out.println(ne);
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        try
        {
            ex=new Execute();
            double a=Double.parseDouble(tf6.getText());
            double b=Double.parseDouble(tf7.getText());
            if(a>b)
            {
                JFrame fr=new JFrame(); 
                JOptionPane.showMessageDialog(fr,"Khách trả chưa đủ"); 
            }
            else
                tf8.setText(String.valueOf(ex.Remain(b,a)));
        }
        catch(ArithmeticException ae){
            ae.printStackTrace();
        }
        catch(NumberFormatException ne){
            ne.printStackTrace();
        }
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        MAHD=tf1.getText();
        Date=tf2.getText();
        MANV=tf3.getText();
        total=Integer.parseInt(tf6.getText());
        CTHD_DTO chdto=new CTHD_DTO(MAHD, Date, MANV, total);
        for(int i=0;i<tb.getRowCount();i++)
        {
            if(tb.isRowSelected(i)==true)           //Thực hiện điền data vào bảng có khóa ngoại sau
            {  
                String a=String.valueOf(tb.getValueAt(i,0));
                String b=String.valueOf(tb.getValueAt(i,1));
                int c=Integer.parseInt(String.valueOf(tb.getValueAt(i,2)));
                int d=Integer.parseInt(String.valueOf(tb.getValueAt(i,3))); 
                SP_DTO sp=new SP_DTO(a,b,c,d);
                listsp.add(sp);
            }
        }
        ch.Save(chdto, listsp);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        try
        {
            tf1.setText("");
            tf2.setText("");
            tf4.setText("");
            tf6.setText("");
            tf7.setText("");
            tf8.setText("");
            sum=0;
            for(int i=0;i<tb.getRowCount();i++)
            {
                if(tb.isRowSelected(i))
                {
                    tb.setValueAt("", i, 0);
                    tb.setValueAt("", i, 1);
                    tb.setValueAt("", i, 2);
                    tb.setValueAt("", i, 3);
                }
            } 
        }catch(NumberFormatException ne){
            ne.printStackTrace();
        }
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        DefaultTableModel models = (DefaultTableModel)tb.getModel();
        models.addRow(new Object[] {});
        numberofrow++;
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        try
        {
            DefaultTableModel models = (DefaultTableModel)tb.getModel();
            models.removeRow(tb.getSelectedRow());
            numberofrow--;
        }catch(ArrayIndexOutOfBoundsException ae){
            JFrame fr=new JFrame(); 
            JOptionPane.showMessageDialog(fr,"Chọn hàng để xóa"); 
        }
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        try
        {
            search=tf9.getText();
            spbll=new SP_BLL();
            SP_DTO product;
            if ((product = spbll.Find(search))!=null){
                if (listmasp.isEmpty()) {
                    listmasp.add(search);
                    tb.setValueAt(product.getMasp(), i, 0);
                    tb.setValueAt(product.getTensp(), i, 1);
                    tb.setValueAt(tf10.getText(), i, 2);
                    tb.setValueAt(product.getDongia(), i, 3);
                    i++;
                } else {
                    int j;
                    for (j = 0; j < listmasp.size(); j++) {
                        if (search.equals(listmasp.get(j))) {
                            JFrame fr = new JFrame();
                            JOptionPane.showMessageDialog(fr, "Trùng mã sản phẩm !");
                            break;
                        }
                    }
                    if (j == listmasp.size()) {
                        listmasp.add(search);
                        tb.setValueAt(product.getMasp(), i, 0);
                        tb.setValueAt(product.getTensp(), i, 1);
                        tb.setValueAt(tf10.getText(), i, 2);
                        tb.setValueAt(product.getDongia(), i, 3);
                        i++;
                    }
                }
            }    
        }
        catch(NumberFormatException ne)
        {
            JFrame fr=new JFrame(); 
            JOptionPane.showMessageDialog(fr,"Bạn cần nhập đủ trường !");
        }
    }//GEN-LAST:event_bt9ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb0;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JTable tb;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf10;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    // End of variables declaration//GEN-END:variables
}
